function withScope(args, context) { return { ...args, workspaceId: args.workspaceId || context.workspaceId || null }; }

export function registerBrowserTools(registry, { browserManager }) {
  registry.register({ name: 'browser_discover', title: 'Discover browser', description: 'Detect an installed Chromium, Chrome, or Edge executable for dependency-free CDP automation.', category: 'browser', readOnly: true, alwaysAvailable: false, keywords: ['browser', 'chrome', 'cdp', 'playwright'], inputSchema: { type: 'object', properties: { force: { type: 'boolean', default: false } } }, execute: async (args) => browserManager.discover(Boolean(args.force)) });
  registry.register({ name: 'browser_launch', title: 'Launch browser', description: 'Launch a persistent-profile Chromium browser with DevTools automation. Headless by default; visible mode supports interactive logins.', category: 'browser', risk: 'process', inputSchema: { type: 'object', properties: { headless: { type: 'boolean', default: true }, profile: { type: 'string', default: 'default' }, url: { type: 'string', default: 'about:blank' }, extraArgs: { type: 'array', items: { type: 'string' } }, executable: { type: 'string' }, reuse: { type: 'boolean', default: true } } }, execute: async (args) => browserManager.launch(args) });
  registry.register({ name: 'browser_instances', title: 'List browser instances', description: 'List browser processes launched by MaskShift.', category: 'browser', readOnly: true, inputSchema: { type: 'object', properties: {} }, execute: async () => browserManager.list() });
  registry.register({ name: 'browser_tabs', title: 'List browser tabs', description: 'List all page targets in a browser instance.', category: 'browser', readOnly: true, inputSchema: { type: 'object', properties: { instanceId: { type: 'string' } } }, execute: async (args) => browserManager.tabs(args.instanceId || null) });
  registry.register({ name: 'browser_new_tab', title: 'Open browser tab', description: 'Create a new browser tab at a URL.', category: 'browser', risk: 'network', inputSchema: { type: 'object', properties: { instanceId: { type: 'string' }, url: { type: 'string', default: 'about:blank' } } }, execute: async (args) => browserManager.newTab(args.instanceId || null, args.url || 'about:blank') });
  registry.register({ name: 'browser_navigate', title: 'Navigate browser', description: 'Navigate a browser tab and wait for the document to load.', category: 'browser', risk: 'network', inputSchema: { type: 'object', required: ['url'], properties: { instanceId: { type: 'string' }, tabId: { type: 'string' }, url: { type: 'string' }, waitUntil: { type: 'string', enum: ['complete', 'domcontentloaded'], default: 'complete' }, timeoutMs: { type: 'integer', minimum: 1000, maximum: 180000, default: 45000 } } }, execute: async (args) => browserManager.navigate(args) });
  registry.register({ name: 'browser_snapshot', title: 'Read browser page', description: 'Return page title, URL, visible text, and a selector map of interactive elements.', category: 'browser', readOnly: true, inputSchema: { type: 'object', properties: { instanceId: { type: 'string' }, tabId: { type: 'string' }, maxTextChars: { type: 'integer', minimum: 1000, maximum: 300000, default: 80000 } } }, execute: async (args) => browserManager.snapshot(args) });
  registry.register({ name: 'browser_accessibility', title: 'Browser accessibility tree', description: 'Return the Chrome accessibility tree for semantic page understanding.', category: 'browser', readOnly: true, inputSchema: { type: 'object', properties: { instanceId: { type: 'string' }, tabId: { type: 'string' }, limit: { type: 'integer', minimum: 1, maximum: 10000, default: 1500 } } }, execute: async (args) => browserManager.accessibility(args) });
  registry.register({ name: 'browser_click', title: 'Click browser element', description: 'Click a CSS selector or page coordinate through the Chrome input pipeline.', category: 'browser', risk: 'external-action', inputSchema: { type: 'object', properties: { instanceId: { type: 'string' }, tabId: { type: 'string' }, selector: { type: 'string' }, x: { type: 'number' }, y: { type: 'number' }, button: { type: 'string', enum: ['left', 'middle', 'right'], default: 'left' }, clickCount: { type: 'integer', minimum: 1, maximum: 3, default: 1 } } }, execute: async (args) => browserManager.click(args) });
  registry.register({ name: 'browser_type', title: 'Type in browser', description: 'Focus an optional CSS selector, type text, and optionally submit with Enter.', category: 'browser', risk: 'external-action', inputSchema: { type: 'object', properties: { instanceId: { type: 'string' }, tabId: { type: 'string' }, selector: { type: 'string' }, text: { type: 'string' }, clear: { type: 'boolean', default: false }, submit: { type: 'boolean', default: false } } }, execute: async (args) => browserManager.type(args) });
  registry.register({ name: 'browser_wait_for', title: 'Wait for browser element', description: 'Wait for a CSS selector to become visible, hidden, attached, or detached.', category: 'browser', readOnly: true, inputSchema: { type: 'object', required: ['selector'], properties: { instanceId: { type: 'string' }, tabId: { type: 'string' }, selector: { type: 'string' }, state: { type: 'string', enum: ['visible', 'hidden', 'attached', 'detached'], default: 'visible' }, timeoutMs: { type: 'integer', minimum: 100, maximum: 180000, default: 30000 } } }, execute: async (args) => browserManager.waitFor(args) });
  registry.register({ name: 'browser_evaluate', title: 'Evaluate browser JavaScript', description: 'Execute arbitrary JavaScript in the active page and return a serializable value.', category: 'browser', risk: 'external-action', inputSchema: { type: 'object', required: ['expression'], properties: { instanceId: { type: 'string' }, tabId: { type: 'string' }, expression: { type: 'string' }, awaitPromise: { type: 'boolean', default: true } } }, execute: async (args) => browserManager.evaluate(args) });
  registry.register({ name: 'browser_screenshot', title: 'Capture browser screenshot', description: 'Capture a viewport or full-page screenshot to a workspace artifact file.', category: 'browser', readOnly: true, inputSchema: { type: 'object', properties: { instanceId: { type: 'string' }, tabId: { type: 'string' }, file: { type: 'string' }, fullPage: { type: 'boolean', default: true }, format: { type: 'string', enum: ['png', 'jpeg', 'webp'], default: 'png' }, quality: { type: 'integer', minimum: 1, maximum: 100, default: 90 }, workspaceId: { type: 'string' } } }, execute: async (args, context) => browserManager.screenshot(withScope(args, context)) });
  registry.register({ name: 'browser_print_pdf', title: 'Print page to PDF', description: 'Render the current browser page to a PDF artifact using Chrome print layout.', category: 'browser', readOnly: true, inputSchema: { type: 'object', properties: { instanceId: { type: 'string' }, tabId: { type: 'string' }, file: { type: 'string' }, landscape: { type: 'boolean', default: false }, printBackground: { type: 'boolean', default: true }, workspaceId: { type: 'string' } } }, execute: async (args, context) => browserManager.printPdf(withScope(args, context)) });
  registry.register({ name: 'browser_console', title: 'Read browser console', description: 'Read recent console messages, exceptions, and browser log entries from the page.', category: 'browser', readOnly: true, inputSchema: { type: 'object', properties: { instanceId: { type: 'string' }, tabId: { type: 'string' }, limit: { type: 'integer', minimum: 1, maximum: 2000, default: 200 } } }, execute: async (args) => browserManager.console(args) });
  registry.register({ name: 'browser_network', title: 'Read browser network trace', description: 'Read recent Chrome DevTools Network events for the page.', category: 'browser', readOnly: true, inputSchema: { type: 'object', properties: { instanceId: { type: 'string' }, tabId: { type: 'string' }, limit: { type: 'integer', minimum: 1, maximum: 5000, default: 300 } } }, execute: async (args) => browserManager.network(args) });
  registry.register({ name: 'browser_close_tab', title: 'Close browser tab', description: 'Close one browser page target.', category: 'browser', risk: 'process', inputSchema: { type: 'object', required: ['tabId'], properties: { instanceId: { type: 'string' }, tabId: { type: 'string' } } }, execute: async (args) => browserManager.closeTab(args.instanceId || null, args.tabId) });
  registry.register({ name: 'browser_close', title: 'Close browser', description: 'Terminate a MaskShift browser instance and its CDP connections.', category: 'browser', risk: 'process', inputSchema: { type: 'object', properties: { instanceId: { type: 'string' } } }, execute: async (args) => browserManager.close(args.instanceId || null) });
}
